name: cpp-build

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-x86:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create build directory
        run: mkdir ./build

      - name: Install dependencies
        run: sudo apt-get update | sudo apt install clang llvm libjsoncpp-dev

      - name: Compile
        run: clang++ -o ./build/creator.o ./src/builder.cpp ./src/folder_tag.cpp ./src/main.cpp -ljsoncpp

      - name: Upload compiled file
        uses: actions/upload-artifact@v4
        with:
          name: build-compiled-x86
          path: ./build/creator.o
          retention-days: 1

  build-apple-silicon:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create build directory
        run: mkdir ./build

      - name: Install dependencies
        run: brew install llvm jsoncpp

      - name: Compile
        run: export CPATH="$(brew --prefix)/include" && export LIBRARY_PATH="$(brew --prefix)/lib" && g++ ./src/builder.cpp ./src/folder_tag.cpp ./src/main.cpp -o ./build/creator.o `pkg-config jsoncpp --cflags --libs`

      - name: Upload compiled file
        uses: actions/upload-artifact@v4
        with:
          name: build-compiled-apple-silicon
          path: ./build/creator.o
          retention-days: 1
